### ISSUE TITLE
array-helpers/src/types.d.ts' is not a module

### ISSUE THREAD

**Issue by Snapperfish** [w3nl/array-helpers#39]
Attempting to import array-helpers gives the following error:

`.../array-helpers/src/types.d.ts' is not a module`

`import { last } from 'array-helpers'`

In a create-react-app node app.

tsConfig.json

`{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}
`

**Comment by w3nl** [comment]
Sorry for the late response, I missed your question.

TS compatibility isn't great yet, but if you check the readme, it works different.

E.g.
```javascript
import { Arr } from 'array-helpers'

var exampleArray = new Arr([1,2,3]);

exampleArray.last;
```

So you build an entity from an existing array, and then you can call all type of functions to get the information from the array.

Maybe I will check later ts types, but I started also a new version: https://github.com/hckrnews/arrays
I focus also more on jsdoc in typescript modus to describe every type: https://github.com/hckrnews/arrays/blob/main/.eslintrc#L30
(https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html)
I will close this issue for now.

If you need the d.ts file, you can also add a PR with your suggestion.
