### ISSUE TITLE
TypeScript types declaration file

### ISSUE THREAD

**Issue by geopic** [w3nl/array-helpers#8]
If you want I can write a TypeScript types declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by w3nl** [comment]
It would be very nice if you do it.

**Comment by geopic** [comment]
Excellent, I'll start on it now.

**Comment by w3nl** [comment]
I have publish version 1.3.0 with typescript support, thanks for your contribution!
